apiVersion: v1
data:
  relay.yaml: |-
    # this is the path that the object graph will get dumped to (in JSON-LD format),
    # you probably shouldn't change it, but you can if you want.
    db: data/relay.jsonld

    # Listener
    listen: 0.0.0.0
    port: 8080

    # Note
    note: "https://hub.docker.com/r/travnewmatic/relay"

    # this section is for ActivityPub
    ap:
      # this is used for generating activitypub messages, as well as instructions for
      # linking AP identities.  it should be an SSL-enabled domain reachable by https.
      host: 'relay.travnewmatic.com'
      blocked_instances:
      - 'bad-instance.example.com'
      - 'another-bad-instance.example.com'
      whitelist_enabled: false
      whitelist:
      - 'good-instance.example.com'
      - 'another.good-instance.example.com'
kind: ConfigMap
metadata:
  name: {{ include "relay.fullname" . }}
